[tool.poetry]
name = "sl"
version = "1"
description = ""
authors = ["Your Name <so.slashua@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
